### ISSUE TITLE
Domain Issues. Says its unsecure.

### ISSUE THREAD

**Issue by talmax1124** [Porter-smith/astro-firebase-svelte-tailwind-starter#1] opened 2023-12-17 05:43 UTC

**Comment by dario24git** [comment] 2023-12-17 08:16
Same problem, i also tested it on vm, auth seems broken

**Comment by Porter-smith** [comment] 2023-12-19 04:28
Sorry your having issues with the template! Could you provide more information of the issue so I can reproduce it ?

Is this what you are referring to ?
<img width="324" alt="Screenshot 2023-12-18 at 9 27 40 PM" src="https://github.com/Porter-smith/astro-firebase-svelte-tailwind-starter/assets/92813718/59d5a63a-206e-4c05-8571-77f284fcc505">

**Comment by dario24git** [comment] 2023-12-19 09:09
![image](https://github.com/Porter-smith/astro-firebase-svelte-tailwind-starter/assets/89135258/6bf48413-aae4-4d40-bf3b-7bca67c79474)

As you can see i have a different flavour of that, not in local host but directly on the domain you assigned to it.

**Comment by Porter-smith** [comment] 2023-12-19 17:23
Thank you for the report! I was able to replicate the issue using Browserstack and found that it is affecting some devices in other locations. Interestingly, it only affects certain devices, and I couldn't replicate it on my own.

From my research so far, it seems that this may have been flagged as a false positive on the Google Safe Browsing list or something similar in some locations. I've filed a report to Google Safe Browsing regarding a false phishing flag, so hopefully, it will be fixed soon.

Based on what I understand, this issue is related to the domain of the deployed site https://astro-firebase-svelte-tailwind-starter.vercel.app/. Therefore, if you use the template for your app, it should be okay, I believe.

I will continue to investigate this issue and try to determine why it was flagged, especially if it's an issue with the template UI itself. If the issue persists, please let me know. Also, if you haven't already, try clearing the browser cache to see if the site information has been updated.

**Comment by Porter-smith** [comment] 2023-12-26 21:50
hi just wanted to leave a update here

the site still had the flag for the suspicious site after I filed a report so I decided to redeploy it with a different domain instead since it hasn't been fixed yet so here is the new domain. Here is new deployed site without issue:

https://astro-firebase-svelte-starter.vercel.app/

**Closed as completed by Porter-smith** 2023-12-26 21:50 UTC
